
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bowling
    volumes:
      - ./db_data:/var/lib/postgresql/data

  web:
    tty: true
    build: .
    # links:
    #   - db_data
    ports:
      - 3000:3000
    volumes:
      - ./:/rails
    # depends_on:
    #   - db_data

volumes:
  db_data:
