
volumes:
  relational-db-data:
services:
  db:
    image: docker.io/mysql/mysql-server:8.0.32
    restart: always
    volumes:
      - source: relational-db-data
        target: /var/lib/mysql
        type: volume
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: cardflight-interview
  web:
    tty: true
    build: .
    links:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/rails
