default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  database: bowling
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
